name: Test install.sh

on:
  pull_request:
    paths:
      - 'install.sh'
  push:
    paths:
      - 'install.sh'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test install.sh (Root-Check und Syntax)
        run: |
          chmod +x install.sh
          sudo BETTY_SKIP_DEPS=true ./install.sh
