name: Update README Version

on:
  release:
    types: [published]

jobs:
  update-readme-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get latest tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      - name: Update README version
        run: |
          sed -i "s/BETTY_VERSION=v[0-9]\+\.[0-9]\+\.[0-9]\+/BETTY_VERSION=${{ steps.get_tag.outputs.tag }}/g" README.md
          sed -i "s/\$env:BETTY_VERSION = 'v[0-9]\+\.[0-9]\+\.[0-9]\+'/\$env:BETTY_VERSION = '${{ steps.get_tag.outputs.tag }}'/g" README.md
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: Update install version to ${{ steps.get_tag.outputs.tag }} [skip ci]" || echo "No changes to commit"
          git push
